### ISSUE TITLE
Can I use the repo in .NET 6.0?

### ISSUE THREAD

**Issue by zydjohnHotmail** [CosineG/OpenCC.NET#1]
Hello:
I want to test the repo to convert some tranditional Chinese text (Hong Kong) to  simplified Chinese text.
I installed the latest version:
PM> Install-Package OpenCCNET -Version 0.2.2
But I found the repo is built with netstandard2.0.
I am coding with Visual Studio 2022 on Windows 10 for .NET 6.0.
I have the following C# code:
using OpenCCNET;
//using System.Text;
        public static string HKToHant(string text)
        {
            ZhUtil.Initialize();
            var textBuilder = new StringBuilder(text, text.Length * 2);
            textBuilder.ConvertVariant(ZhDictionary.HKVariantsReversed);
            return textBuilder.ToString();
        }
But I got compiler error:
Error	CS0246	The type or namespace name 'StringBuilder' could not be found

If I change the code, so it looks like:
using OpenCCNET;
using System.Text;
        public static string HKToHant(string text)
        {
            ZhUtil.Initialize();
            var textBuilder = new StringBuilder(text, text.Length * 2);
            textBuilder.ConvertVariant(ZhDictionary.HKVariantsReversed);
            return textBuilder.ToString();
        }
Then I got another compiler error:
Error	CS1061	'StringBuilder' does not contain a definition for 'ConvertVariant' and no accessible extension method 'ConvertVariant' accepting a first argument of type 'StringBuilder' could be found.
How can you fix this issue?
I suggest to upgrade to target .NET 6.0, since it is in long-term support, netstandard2.0. is too old.
Thanks,

**Comment by CosineG** [comment]
Do you want to modify this library or just use it? `ConvertVariant`is the extension method I write for `StringBuilder`, but if you just want to call API, there is no need to use it. To convert tranditional Chinese(Hong Kong) to simplified Chinese, just use the extension method `ToHansFromHK()`  of `string`, like
```csharp
using OpenCCNET;

ZhUtil.Initialize();
Console.WriteLine("你好現在正在測試".ToHansFromHK());
```
![image](https://user-images.githubusercontent.com/33339051/157145341-7d26212f-6141-41ad-bb41-9839849315d0.png)
I test it on .NET 6 and it works well.

Besides, the reason I chose .net standard2.0  is that it is the minimum requirement of Jieba.NET. The higher version of .NET should be able to use this library.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks for your reply, I have done some testing for both .Net 5.0 & .Net 6.0 in a console project.
I think it may work, but from the console screen, I see only garbage code:
The following is my C# code:
using OpenCCNET;
using System;

namespace ConsoleApp1
{
    internal class Program
    {
        static void Main(string[] args)
        {
            ZhUtil.Initialize();
            Console.WriteLine("你好現在正在測試".ToHansFromHK());
            Console.WriteLine("Hello World!");
        }
    }
}
I am using Windows 10 English version.  Do I have to do some settings to see the Chinese characters?
By the way, is it possible to write the converted Chinese in a PDF or PNG file, so I can see it even from the console program, it looks garbage.
Please advise,
Thanks
![ShowHKChineseNOK](https://user-images.githubusercontent.com/45263518/157233188-65096712-7709-4e9c-831a-caf48331a092.png)
,

**Comment by CosineG** [comment]
Hi, I find a soulution of the chinese display on Windows 10 English version from [Microsoft Community](https://answers.microsoft.com/en-us/windows/forum/windows_8-performance/notepad-cant-display-chinese-language/a3f69499-bae1-481a-ac31-0e23d999210b), you can see if it works.
And `PdfSharpCore` can convert text to PDF, you can get it from nuget. I test it like:
```csharp
ZhUtil.Initialize();
var document = new PdfDocument();
var page = document.AddPage();
var gfx = XGraphics.FromPdfPage(page);
var font = new XFont("SimHei", 20, XFontStyle.Regular);
gfx.DrawString("你好現在正在測試".ToHansFromHK(), font, XBrushes.Black, new XRect(20, 20, page.Width, page.Height), XStringFormats.Center);
document.Save("test.pdf");
```
can get:
![image](https://user-images.githubusercontent.com/33339051/157242641-485ccb78-0a72-4aab-b3f2-f4452a9c4b28.png)
But I'm not sure if Windows English version contains chinese fonts like "SimHei".

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks, it works now!
