### ISSUE TITLE
在 F# 交互环境下会崩溃

### ISSUE THREAD

**Issue by ijklam** [CosineG/OpenCC.NET#2]
如图
![image](https://user-images.githubusercontent.com/43789618/164582848-d80d6703-b5a3-454d-b312-0c3c67fd4acc.png)

**Comment by CosineG** [comment]
你好，我看提示原因是Jieba.NET库找不到对应的资源文件所以报错，请问你是否下载了仓库中的Dictionary(字典文件)和JiebaResource(Jieba.NET运行所需的词典及其它数据文件)文件夹放入项目程序所在目录？
其实这两个文件夹我有打包进Nuget包里，但是没能实现让他们在程序生成时自动复制到输出目录，所以目前只能手工放置。

**Comment by ijklam** [comment]
可以了，要将工作目录设置成包的目录
![image](https://user-images.githubusercontent.com/43789618/164585863-1c4aa19c-2f74-4452-ae64-5819ca3e074a.png)

**Comment by cipchk** [comment]
> 你好，我看提示原因是Jieba.NET库找不到对应的资源文件所以报错，请问你是否下载了仓库中的Dictionary(字典文件)和JiebaResource(Jieba.NET运行所需的词典及其它数据文件)文件夹放入项目程序所在目录？ 其实这两个文件夹我有打包进Nuget包里，但是没能实现让他们在程序生成时自动复制到输出目录，所以目前只能手工放置。

建议将这个点在 README 中提示。

**Comment by CosineG** [comment]
@cipchk 现在还会有这个问题吗？最新版本应该已经会自动把资源文件复制到程序输出目录了

**Comment by cipchk** [comment]
@CosineG 控制台没有问题，但是WebApi还会有路径问题。

**Comment by CosineG** [comment]
@cipchk 我没试过webapi，如果需要的话，`ZhConverter.Initialize()`是支持自定义资源路径的
