### ISSUE TITLE
Old code didn't work for new version of the repo.

### ISSUE THREAD

**Issue by zydjohnHotmail** [CosineG/OpenCC.NET#3]
Hello:
Today, I found the repo has a new release for NUGET, so I installed the new version (1.01), and try to test it, the follwing is the C# code:
ZhUtil.Initialize();
var document = new PdfDocument();
var page = document.AddPage();
var gfx = XGraphics.FromPdfPage(page);
var font = new XFont("SimHei", 20, XFontStyle.Regular);
gfx.DrawString("你好現在正在測試".ToHansFromHK(), font, XBrushes.Black, new XRect(20, 20, page.Width, page.Height), XStringFormats.Center);
document.Save("test.pdf");
But the code didn't get compiled, I got error message:
Error	CS0103	The name 'ZhUtil' does not exist in the current context.
I am using Visual Studio 2022, my project is WinForms targetting .NET 6.0.
Please advise on how to fix this issue.
Thanks,

**Comment by CosineG** [comment]
Sorry, I adjusted the project structure in the least version. `ZhUtil` is now abandoned, just use `ZhConverter.Initialize()` instead. I will add the English version of readme to the project later.

**Comment by zydjohnHotmail** [comment]
Hi,
Thanks for your info, it is working now!
